### ISSUE TITLE
Let $bind work with link relations instead of paths

### ISSUE THREAD

**Issue by odrotbohm** [lbovet/hybind#1]
Hypermedia is about clients not knowing about URIs upfront but following links transparently. Hybind unfortunately seems to build URIs in its `$bind` function as [documented on the website](https://lbovet.github.io/hybind/).

As you seem to work with HAL and expect a root URI to be set anyway, is there a chance you rather inspect the response of the root URI, and use the link that's given for the string handed to `$bind`? That would cause Hybind to actually use hypermedia and not treat HAL as a pure data transportation format.

**Comment by lbovet** [comment]
It actually works both ways. If you $load the root API, it will create the properties for the links and create empty bound objects configured with the correct self-link. In this case, you don't have to call $bind on the "children".
The goal is to let user choose if they want to follow links or shortcut them. Practice seems to show that people do both...
Thanks for pointing this. I will try to update the doc accordingly.

**Comment by odrotbohm** [comment]
Thanks for the explanation! If that already works, even better :). A hint in the docs would be very appreciated.

**Comment by lbovet** [comment]
BTW, is there a way to know if a link points to a collection? Currently, on
$load, the child would be created as an object  instead of an array. We
lose the benefit of using an array as model and need to map _embedded
manually. I haven't seen such an info in the profile.

Le jeu. 1 sept. 2016 22:29, Oliver Gierke notifications@github.com a
écrit :
